@startuml
skinparam componentStyle uml2

node "Peer 1" {
  component Component1
}

node "Peer 2" {
  component Component2
}

node "Peer 3" {
  component Component3
}

Component1 --> Component2
Component2 --> Component3
Component3 --> Component1

@enduml
